### ISSUE TITLE
Check status on existing bugs

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#15]
For each of the following bugs, evaluate their priority and decide if they are to be fixed during this industrialization phases or later.

**7 (2986): When adding ports on cluster, not all instances are updated accordingly**
Open graphical editors for (see test-7.zip):
* System in model.poosl
* Cluster BusBasedNetwork() in busbased.poosl
Adding a port (through the graphical editor) on the cluster class BusBasedNetwork() in busbased.poosl does not update the system diagram for model.poosl.

**18 (1469): Ports of instances move when a channel is created in the graphical view** 
When a channel is created in the graphical view of a cluster class then the instance ports that the channel connects move to the top-left corner of the instance.

**15 (1556): Tasks as class name**
If you name a class Task1, and then try to navigate to it (not through F3, but with CTRL+ mouse) then you may end up on the Eclipse Issues.

**54 (1176): Unknown handle warning (in the error log only) from the inspection of a local variable**
Happens in the following cases:
* termination of a process instance
* leaving a process method call
The problem seems to be that double-clicking in the ExecutionTree results in first performing a transition, and afterwards inspecting the (old) variables.

**8 (new): Change Value is offered on sub-variables in StackTrace Variables**
Change Value is offered on sub-variables in StackTrace Variables windows, but is always refused by Rotalumis. It would be better not to offer this functionality on sub-variables.

**60 (new): Race condition on opening communication diagram**
Start a fresh Eclipse, then start a debug session and "open communication diagram". Opening a Sirius diagram for the first time takes a little while. Once the Sirius diagram is shown, there are three possible scenarios (race condition?):
* everything works fine;
* in the communication diagram the communication elements (such as message counters) are hidden;
* multiple pop-up windows are shown reporting that the model has changed.

**Comment by mypsycho** [comment]
Dispatch in independent ticket for teamwork purpose.
See query https://github.com/ObeoNetwork/POOSL/issues?q=label%3Alegacy+
