### ISSUE TITLE
Centralize documentation

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#17]
Having only one documentation (aggregation of the 2 existing one) that is deployed in several places (both Eclipse IDE and website) during Maven build would ease the maintenance.

**Comment by wpiers** [comment]
TODO deploy the current HTML on github pages

**Comment by mypsycho** [comment]
Entry point is in readme of project.

**Comment by wpiers** [comment]
https://obeonetwork.github.io/POOSL/
