### ISSUE TITLE
Improve cyclomatic complexity

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#22]
Some method in the code base will be refactored to improve their score (using sub-method calls, reduce their scope etc.). For example, see:
• nl.esi.poosl.rotalumisclient.debug.PooslDebugTarget.dispatchResponse(Response)
• nl.esi.poosl.rotalumisclient.debug.PooslDebugTarget.debugEventSetListener.new
IDebugEventSetListener() {…}.handleDebugEvents(DebugEvent[]).

**Comment by wpiers** [comment]
Postponed to M3, guidelines will be written to avoid introducing new issues.

**Comment by mypsycho** [comment]
Checkstyle CyclomaticComplexity rule tracks this issue.
It will be fixed with the flow.
