### ISSUE TITLE
Upgrade to the last version of Sirius, Xtext and Eclipse

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#25]

**Comment by mypsycho** [comment]
Because of RCPTT we must target Eclipse 2020-03 (aka 4.15)

**Comment by wpiers** [comment]
RCPTT uses an Eclipse UI method here:
https://git.eclipse.org/r/plugins/gitiles/rcptt/org.eclipse.rcptt/+/master/rcp/contexts/org.eclipse.rcptt.ctx.workbench.ui/src/org/eclipse/rcptt/ctx/workbench/ui/views/SelectViewDialog.java#262

That no longer exists in the latest eclipse version (4.16), cf https://projects.eclipse.org/projects/eclipse/releases/4.16.0/bugs
Which refers to https://bugs.eclipse.org/bugs/show_bug.cgi?id=149652

So to use RCPTT we must stay with an older version, 4.15.
