### ISSUE TITLE
Align with Capella look and feel

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#37]
Background color for containers, port styling, …

**Comment by mypsycho** [comment]
For Class Diagram, CDB colors&shapes could apply : [Capella Class Diagram](https://en.wikipedia.org/wiki/Capella_(engineering)#/media/File:Capella_CDB.png)
For Composite Structure diagram, 2 diagrams are related, both are only partially covered:
* [Logical Architecture](https://en.wikipedia.org/wiki/Capella_(engineering)#/media/File:Capella_LAB.png)
* [Physical Architecture ](https://en.wikipedia.org/wiki/Capella_(engineering)#/media/File:Capella_PAB.png)

**Comment by mypsycho** [comment]
If Composite Structure is aligned with 'Logical Architecture', port orientation is defined by direction of message attached to port.

**Comment by mypsycho** [comment]
![image](https://user-images.githubusercontent.com/823389/132868377-a4e7486b-bba2-4201-a278-2285396d5e22.png)

cluster class: Yellow squared-corner with "Component" icon
process class : Blue round-corner with "Component" icon
port (proposition): square with name outside.

**Comment by mypsycho** [comment]
Proposition for Composite diagram:
Currently
<img width="345" alt="Capture_composite" src="https://user-images.githubusercontent.com/823389/133811579-df09ef9f-5bfa-493d-a48a-c283e1d3e20d.PNG">
Proposition
<img width="314" alt="Capture_composite_capella" src="https://user-images.githubusercontent.com/823389/133812106-0f40b88a-c8cc-46e1-a05b-5b36e170f135.PNG">

**Comment by mypsycho** [comment]
Composite diagram detail:
cluster class: Yellow round-corner with "UML-Component" icon
process class : Blue round-corner with "UML-Component" icon
port : square with name outside.

**Comment by mypsycho** [comment]
Proposition for Class diagram:
Currently
<img width="384" alt="Capture_class" src="https://user-images.githubusercontent.com/823389/133823621-3e20fe7f-594b-4678-aeb4-703f862849a7.PNG">
Proposition
<img width="214" alt="Capture_class_capella" src="https://user-images.githubusercontent.com/823389/133823662-5b6005a2-af84-4f23-b308-b75127dd42e7.PNG">

**Comment by mypsycho** [comment]
Data class: Round-corner beige with "uml-class" icon
