### ISSUE TITLE
Provide a way to package libraries

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#39]
POOSL IDE should provide a way to provide libraries packaged in a plugin. The benefit of shipping
models in plugins would be:
• Updateatable libraries using P2 mechanism
• Immutability
• Building custom product with business oriented libraries

After discussing this matter with TNO-ESI it appears that this feature would require some work due to exchange mechanism between POOSL IDE and Rotalumis.

**Comment by mypsycho** [comment]
We could provide a 'import' feature based on registered models from plugins.

**Comment by mypsycho** [comment]
Set P3 as Example feature should cover the need.
