### ISSUE TITLE
Unpack nl.tue.rotalumis.executables in product

### ISSUE THREAD

**Issue by mypsycho** [ObeoNetwork/POOSL#46]
Using unpacked plugin, we could avoid unzipping an executable in temp zone.

This mode could work in a product.
In dev env, target platform loader does not provide unpack plugin.

**Comment by mypsycho** [comment]
https://eclipsesource.com/blogs/2009/01/20/tip-eclipse-bundleshape

We must set Eclipse-BundleShape in nl.tue.rotalumis.executables to dir.
We should test it locally before requeting the update.

**Comment by mypsycho** [comment]
Once nl.tue.rotalumis.executables is in 'dir' shape.
We only need to update org.eclipse.poosl.rotalumisclient.runner.RotalumisRunner to remove the useless unzip.
Update
* createRotalumisFile() to get the proper path
* getPluginRotalumis() to remove the file creation.

**Comment by MartijnKTue** [comment]
Change has been made on the integration branch, can this be tested.

**Comment by mypsycho** [comment]
> 
> 
> I get almost the same error:
> 
> ```
> session context was:(profile=epp.package.dsl, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=[R]nl.tue.rotalumis.executables 4.2.0.202110180801 --> [R]nl.tue.rotalumis.executables 4.2.0.202110251205, action=org.eclipse.equinox.internal.p2.touchpoint.eclipse.actions.ChmodAction).
> The artifact /home/~/Programming/Poosl/IDE-DIR/eclipse/plugins/nl.tue.rotalumis.executables_4.2.0.202110251205.jar is not a directory.
> ```

Property 'Eclipse-BundleShape = dir' desappeared from Manifest.
ChmodAction cannot work without it.

**Comment by MartijnKTue** [comment]
weird. I did not remove that.
Let me try this again.

**Comment by MartijnKTue** [comment]
For linux that seems to have worked.

**Comment by MartijnKTue** [comment]
It also seems to run under windows.
