### ISSUE TITLE
Fix PooslEditorPreferenceDialog size

### ISSUE THREAD

**Issue by mypsycho** [ObeoNetwork/POOSL#47]
When opening a poosl file, a choice is made to the user to select editor type.

The dialog box does not display all the choices properly.

As the dialog box is a radio group, maybe a standard message dialog could be used.

**Comment by wpiers** [comment]
Could you check that https://github.com/ObeoNetwork/POOSL/commit/c05dfc7392caccc22e482a0b77cda4c4461aa8ec fixes the issue ? it solved #73 already

**Comment by mypsycho** [comment]
Ok for me.
