### ISSUE TITLE
Tests products on Mac and Linux

### ISSUE THREAD

**Issue by mypsycho** [ObeoNetwork/POOSL#53]
Once a tag is set, products are attached to it by workflow.

Mac and Linux product have not been tested yet

**Comment by wpiers** [comment]
There seems to be an issue with macos, which fails to run the executable

**Comment by wpiers** [comment]
The product has been tested on Mac & Linux. No issues were detected on Linux. On Mac:
 * the rotalumnis executable couldn't be launched #72
 * for one user the "open poosl file" dialog only show the "Textual" option, not the 2 graphical ones #73
