### ISSUE TITLE
Optimize plugins contents

### ISSUE THREAD

**Issue by wpiers** [ObeoNetwork/POOSL#7]
Integrate nl.esi.poosl.xsd and nl.esi.poosl.generatedxmlclasses into nl.esi.poosl.rotalumisclient.

**Comment by wpiers** [comment]
org.eclipse.poosl.legacysupport depends on nl.esi.poosl.generatedxmlclasses. We'll have to check first if it makes sense to make legacysupport depends on rotalumnisclient.
The xsd definition is only used to generate the java classes so having it in a separate project is not a bundle size concern.

**Comment by mypsycho** [comment]
xsd schema have been moved as part of org.eclipse.poosl.generatedxmlclasses project in the same logic as *.ecore is in Model project.
I think it would be an error to link rotamulisclient and legacy: 
they shares no purpose and only use the same xml encoding.

**Comment by wpiers** [comment]
Perfect
